=== miztli/hybris/b2b_acc/hybris/bin/platform/ext/core/resources/audit/audit.xsd
<?xml version="1.0" encoding="UTF-8"?>
<!--
 [y] hybris Platform

 Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.

 This software is the confidential and proprietary information of SAP
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with SAP.
-->
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema" elementFormDefault="qualified">
    <xs:element name="audit-report-config">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="given-root-type" minOccurs="1" maxOccurs="1"/>
                <xs:element ref="types"/>
            </xs:sequence>
            <xs:attribute type="name" name="name" use="required"/>
            <xs:attribute type="xs:string" name="auditRecordsProvider"/>
            <xs:attribute type="xs:string" name="mode"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="types">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="type" minOccurs="1" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="type">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="atomic-attributes" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="reference-attributes" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="virtual-attributes" minOccurs="0" maxOccurs="1"/>
                <xs:element ref="relation-attributes" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="name" name="code" use="required"/>
            <xs:attribute type="xs:string" name="displayName" use="optional"/>
            <xs:attribute type="xs:string" name="displayKey" use="optional"/>
            <xs:attribute type="xs:string" name="mode" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="atomic-attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="atomic-attribute" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="reference-attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="reference-attribute" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="virtual-attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="virtual-attribute" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>
    <xs:element name="relation-attributes">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="relation-attribute" minOccurs="0" maxOccurs="unbounded"/>
            </xs:sequence>
        </xs:complexType>
    </xs:element>

    <xs:element name="resolves-by">
        <xs:complexType>
            <xs:attribute type="xs:string" name="resolverBeanId" use="optional"/>
            <xs:attribute type="xs:string" name="expression" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="atomic-attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resolves-by" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="name" name="qualifier" use="required"/>
            <xs:attribute type="xs:string" name="displayName" use="optional"/>
            <xs:attribute type="xs:string" name="displayKey" use="optional"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="reference-attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resolves-by" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="name" name="qualifier" use="required"/>
            <xs:attribute type="xs:string" name="displayName" use="optional"/>
            <xs:attribute type="xs:string" name="displayKey" use="optional"/>
            <xs:attribute type="xs:boolean" name="many" use="optional"/>
            <xs:attribute type="xs:string" name="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="virtual-attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resolves-by" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="name" name="expression" use="optional"/>
            <xs:attribute type="xs:string" name="displayName" use="optional"/>
            <xs:attribute type="xs:string" name="displayKey" use="optional"/>
            <xs:attribute type="xs:boolean" name="many" use="optional"/>
            <xs:attribute type="xs:string" name="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="relation-attribute">
        <xs:complexType>
            <xs:sequence>
                <xs:element ref="resolves-by" minOccurs="0" maxOccurs="1"/>
            </xs:sequence>
            <xs:attribute type="xs:string" name="relation" use="required"/>
            <xs:attribute type="xs:string" name="displayName" use="optional"/>
            <xs:attribute type="xs:string" name="displayKey" use="optional"/>
            <xs:attribute type="xs:boolean" name="many" use="optional"/>
            <xs:attribute type="xs:string" name="type" use="required"/>
        </xs:complexType>
    </xs:element>
    <xs:element name="given-root-type" type="xs:string"/>
    <xs:simpleType name="name">
        <xs:annotation>
            <xs:documentation>A non-empty string.</xs:documentation>
        </xs:annotation>
        <xs:restriction base="xs:string">
            <xs:minLength value="1"/>
        </xs:restriction>
    </xs:simpleType>
</xs:schema>

=== miztli/hybris/platform_only_recipe/hybris/bin/platform/ext/core/resources/audit.test/user-address-country.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
 [y] hybris Platform

 Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.

 This software is the confidential and proprietary information of SAP
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with SAP.
-->
<audit-report-config name="userAddressCountry" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="../audit/audit.xsd">
	<given-root-type>User</given-root-type>
	<types>
		<type code="User" displayName="User">
			<atomic-attributes>
				<atomic-attribute qualifier="name" displayName="name"/>
				<atomic-attribute qualifier="uid" displayName="uid"/>
			</atomic-attributes>
			<virtual-attributes>
				<virtual-attribute expression="owner" type="Address" many="true" displayName="owned addresses"/>
			</virtual-attributes>
		</type>

		<type code="Address">
			<atomic-attributes>
				<atomic-attribute qualifier="streetname" displayName="street"/>
			</atomic-attributes>
			<reference-attributes>
				<reference-attribute qualifier="country" displayName="country" type="Country"/>
				<reference-attribute qualifier="region" displayName="region" type="Region"/>
			</reference-attributes>
		</type>


		<type code="Country">
			<atomic-attributes>
				<atomic-attribute qualifier="isocode" displayName="isocode"/>
				<atomic-attribute qualifier="name" displayName="name"/>
			</atomic-attributes>
			<!--<reference-attributes>-->
				<!--<attribute qualifier="regions" displayName="regions" type="Region"/>-->
			<!--</reference-attributes>-->
			<virtual-attributes>
				<virtual-attribute expression="country" type="Region" many="true" displayName="regions"/>
			</virtual-attributes>
		</type>

		<type code="Region">
			<atomic-attributes>
				<atomic-attribute qualifier="isocode" displayName="isocode"/>
				<atomic-attribute qualifier="name" displayName="name"/>
			</atomic-attributes>
		</type>
	</types>
</audit-report-config>

=== miztli/hybris/bin/platform/ext/core/resources/audit.test/user-with-displayname-audit.xml
<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<!--
 [y] hybris Platform

 Copyright (c) 2018 SAP SE or an SAP affiliate company. All rights reserved.

 This software is the confidential and proprietary information of SAP
 ("Confidential Information"). You shall not disclose such Confidential
 Information and shall use it only in accordance with the terms of the
 license agreement you entered into with SAP.
-->
<audit-report-config name="UserWithDisplayNameConfig" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                     xsi:noNamespaceSchemaLocation="../audit/audit.xsd">
    <given-root-type>User</given-root-type>
    <types>
        <type code="User" displayName="User">
            <atomic-attributes>
                <atomic-attribute qualifier="uid" displayName="uid"/>
                <atomic-attribute qualifier="name" displayName="nAmE"/>
                <atomic-attribute qualifier="description" displayName="userDescription"/>
            </atomic-attributes>
            <reference-attributes>
                <reference-attribute qualifier="defaultPaymentAddress" displayName="defaultPaymentAddress"
                                     type="Address"/>
            </reference-attributes>
            <virtual-attributes>
                <virtual-attribute expression="owner" type="Address" many="true" displayName="owned Addresses"/>
            </virtual-attributes>
            <relation-attributes>
                <relation-attribute relation="principalGroupRelation" displayName="User_Groups" many="true"
                                    type="UserGroup"/>
            </relation-attributes>
        </type>
        <type code="Address">
            <atomic-attributes>
                <atomic-attribute qualifier="streetname" displayName="streeT"/>
                <atomic-attribute qualifier="appartment" displayName="aPpartment"/>
            </atomic-attributes>
        </type>
        <type code="UserGroup">
            <atomic-attributes>
                <atomic-attribute qualifier="locName" displayName="lOcName"/>
            </atomic-attributes>
        </type>
    </types>
</audit-report-config>
